//jDownloader - Downloadmanager
//Copyright (C) 2013  JD-Team support@jdownloader.org
//
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//GNU General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with this program.  If not, see <http://www.gnu.org/licenses/>.
package jd.plugins.hoster;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.appwork.net.protocol.http.HTTPConstants;
import org.appwork.storage.JSonMapperException;
import org.appwork.storage.TypeRef;
import org.appwork.utils.StringUtils;
import org.appwork.utils.parser.UrlQuery;
import org.jdownloader.plugins.controller.LazyPlugin;

import jd.PluginWrapper;
import jd.http.Browser;
import jd.plugins.Account;
import jd.plugins.Account.AccountType;
import jd.plugins.AccountInfo;
import jd.plugins.AccountInvalidException;
import jd.plugins.AccountRequiredException;
import jd.plugins.AccountUnavailableException;
import jd.plugins.DownloadLink;
import jd.plugins.DownloadLink.AvailableStatus;
import jd.plugins.HostPlugin;
import jd.plugins.LinkStatus;
import jd.plugins.MultiHostHost;
import jd.plugins.MultiHostHost.MultihosterHostStatus;
import jd.plugins.PluginException;
import jd.plugins.PluginForHost;
import jd.plugins.components.MultiHosterManagement;

@HostPlugin(revision = "$Revision: 53124 $", interfaceVersion = 3, names = { "dropx.to" }, urls = { "" })
public class DropxTo extends PluginForHost {
    private static final String          API_BASE                         = "https://dropx.to/api/jd";
    private static MultiHosterManagement mhm                              = new MultiHosterManagement("dropx.to");
    private static final int             defaultMAXCHUNKS                 = 1;
    private static final String          PROPERTY_DOWNLOADLINK_directlink = "directlink";
    private static final String          PROPERTY_DOWNLOADLINK_maxchunks  = "maxchunks";
    private static final String          PROPERTY_DOWNLOADLINK_resumable  = "resumable";

    public DropxTo(final PluginWrapper wrapper) {
        super(wrapper);
        this.enablePremium("https://" + getHost() + "/");
    }

    @Override
    public LazyPlugin.FEATURE[] getFeatures() {
        return new LazyPlugin.FEATURE[] { LazyPlugin.FEATURE.MULTIHOST, LazyPlugin.FEATURE.API_KEY_LOGIN };
    }

    @Override
    public String getAGBLink() {
        return "https://" + getHost() + "/regulamin";
    }

    @Override
    public Browser createNewBrowserInstance() {
        final Browser br = super.createNewBrowserInstance();
        br.setFollowRedirects(true);
        br.setCookiesExclusive(true);
        br.getHeaders().put(HTTPConstants.HEADER_REQUEST_USER_AGENT, "JDownloader");
        br.getHeaders().put(HTTPConstants.HEADER_REQUEST_ACCEPT, "application/json");
        /* Custom error codes are returned along with these http response codes. */
        br.setAllowedResponseCodes(new int[] { 400, 401, 403, 500, 503 });
        return br;
    }

    private void setAuthHeader(final Browser br, final Account account) {
        /* API token is generated by the user in the DropX panel (Security -> JDownloader). */
        br.getHeaders().put(HTTPConstants.HEADER_REQUEST_AUTHORIZATION, "Bearer " + account.getPass());
    }

    @Override
    public boolean isResumeable(final DownloadLink link, final Account account) {
        return link.getBooleanProperty(PROPERTY_DOWNLOADLINK_resumable, true);
    }

    public int getMaxChunks(final DownloadLink link) {
        int chunks = link.getIntegerProperty(PROPERTY_DOWNLOADLINK_maxchunks, defaultMAXCHUNKS);
        if (chunks > 1) {
            /* JDownloader expects a negative value if a specific number of chunks (>1) shall be used. */
            chunks = -chunks;
        }
        return chunks;
    }

    @Override
    public AvailableStatus requestFileInformation(final DownloadLink link) throws Exception {
        /* Filesize and filename are only known after generating the direct-URL. */
        return AvailableStatus.UNCHECKABLE;
    }

    @Override
    public void handleFree(final DownloadLink link) throws Exception {
        /* Free downloads are not supported by this multihoster. */
        throw new AccountRequiredException();
    }

    @Override
    public void handlePremium(final DownloadLink link, final Account account) throws Exception {
        throw new PluginException(LinkStatus.ERROR_PLUGIN_DEFECT);
    }

    @Override
    public void handleMultiHost(final DownloadLink link, final Account account) throws Exception {
        this.setAuthHeader(br, account);
        final String directlinkproperty = this.getHost() + "_" + PROPERTY_DOWNLOADLINK_directlink;
        final String storedDirecturl = link.getStringProperty(directlinkproperty);
        final String dllink;
        if (storedDirecturl != null) {
            logger.info("Trying to re-use stored directurl: " + storedDirecturl);
            dllink = storedDirecturl;
        } else {
            final UrlQuery query = new UrlQuery();
            query.appendEncoded("url", link.getDefaultPlugin().buildExternalDownloadURL(link, this));
            br.postPage(API_BASE + "/download", query);
            final Map<String, Object> entries = this.checkErrors(br, account, link);
            final Map<String, Object> data = (Map<String, Object>) entries.get("data");
            dllink = (String) data.get("link");
            if (StringUtils.isEmpty(dllink)) {
                mhm.handleErrorGeneric(account, link, "dllinknull", 50, 5 * 60 * 1000l);
            }
            // link.setFinalFileName((String) data.get("filename"));
            // link.setVerifiedFileSize(Long.parseLong(data.get("filesize").toString()));
            link.setProperty(PROPERTY_DOWNLOADLINK_maxchunks, ((Number) data.get("maxchunks")).intValue());
            link.setProperty(PROPERTY_DOWNLOADLINK_resumable, ((Boolean) data.get("resumable")).booleanValue());
        }
        try {
            dl = jd.plugins.BrowserAdapter.openDownload(br, link, dllink, this.isResumeable(link, account), this.getMaxChunks(link));
            if (!this.looksLikeDownloadableContent(dl.getConnection())) {
                br.followConnection(true);
                mhm.handleErrorGeneric(account, link, "Unknown download error", 50, 5 * 60 * 1000l);
            }
        } catch (final Exception e) {
            if (storedDirecturl != null) {
                link.removeProperty(directlinkproperty);
                throw new PluginException(LinkStatus.ERROR_RETRY, "Stored directurl expired", e);
            } else {
                throw e;
            }
        }
        /* Store direct-URL for later re-use (does not consume traffic again while still valid). */
        link.setProperty(directlinkproperty, dllink);
        this.dl.startDownload();
    }

    @Override
    public AccountInfo fetchAccountInfo(final Account account) throws Exception {
        final AccountInfo ai = new AccountInfo();
        this.setAuthHeader(br, account);
        /* 1. Account information */
        br.postPage(API_BASE + "/account", new UrlQuery());
        final Map<String, Object> entries = this.checkErrors(br, account, null);
        final Map<String, Object> accountmap = (Map<String, Object>) entries.get("account");
        final String type = (String) accountmap.get("type");
        if (type == null || type.equalsIgnoreCase("free")) {
            account.setType(AccountType.FREE);
            ai.setTrafficLeft(0);
            ai.setExpired(true);
        } else {
            account.setType(AccountType.PREMIUM);
            ai.setStatus(AccountType.PREMIUM.getLabel() + " | " + type);
            ai.setTrafficMax(((Number) accountmap.get("trafficmax_daily")).longValue());
            ai.setTrafficLeft(((Number) accountmap.get("trafficleft")).longValue());
            /* timeleft is null if the account never expires. */
            final Object timeleftO = accountmap.get("timeleft");
            if (timeleftO != null) {
                ai.setValidUntil(System.currentTimeMillis() + ((Number) timeleftO).longValue());
            }
        }
        account.setConcurrentUsePossible(true);
        /* 2. List of supported hosts */
        br.postPage(API_BASE + "/hosts", new UrlQuery());
        final Map<String, Object> hostsResponse = this.checkErrors(br, account, null);
        final List<Map<String, Object>> supportedhosts = (List<Map<String, Object>>) hostsResponse.get("supportedhosts");
        final List<MultiHostHost> mhosts = new ArrayList<MultiHostHost>();
        for (final Map<String, Object> hostinfo : supportedhosts) {
            final MultiHostHost mhost = new MultiHostHost((String) hostinfo.get("host"));
            mhost.setMaxChunks(((Number) hostinfo.get("maxChunks")).intValue());
            mhost.setMaxDownloads(((Number) hostinfo.get("maxDownloads")).intValue());
            mhost.setResumable(((Boolean) hostinfo.get("resumable")).booleanValue());
            if (!((Boolean) hostinfo.get("currently_working")).booleanValue()) {
                mhost.setStatus(MultihosterHostStatus.DEACTIVATED_MULTIHOST);
            }
            mhosts.add(mhost);
        }
        ai.setMultiHostSupportV2(this, mhosts);
        return ai;
    }

    /**
     * Parses the API response and throws the appropriate exception on error. </br>
     * Returns the parsed json map on success.
     */
    private Map<String, Object> checkErrors(final Browser br, final Account account, final DownloadLink link) throws PluginException, InterruptedException {
        Map<String, Object> entries = null;
        try {
            entries = restoreFromString(br.getRequest().getHtmlCode(), TypeRef.MAP);
        } catch (final JSonMapperException e) {
            final String msg = "Invalid API response";
            if (link != null) {
                throw new PluginException(LinkStatus.ERROR_TEMPORARILY_UNAVAILABLE, msg, 60 * 1000l);
            } else {
                throw new AccountUnavailableException(msg, 60 * 1000l);
            }
        }
        if (((Boolean) entries.get("success")).booleanValue()) {
            /* No error */
            return entries;
        }
        final int status = ((Number) entries.get("status")).intValue();
        final String msg = (String) entries.get("msg");
        long retryMillis = 5 * 60 * 1000l;
        final Object retryO = entries.get("retry_in_seconds");
        if (retryO != null) {
            retryMillis = ((Number) retryO).longValue() * 1000l;
        }
        if (status >= 1 && status <= 50) {
            /* Permanent account errors */
            throw new AccountInvalidException(msg);
        } else if (status >= 51 && status <= 100) {
            /* Temporary account errors */
            throw new AccountUnavailableException(msg, retryMillis);
        } else if (status >= 101 && status <= 200) {
            /* Download errors */
            if (status == 101) {
                /* File is offline */
                throw new PluginException(LinkStatus.ERROR_FILE_NOT_FOUND);
            }
            mhm.handleErrorGeneric(account, link, msg, 50, retryMillis);
            /* Unreachable code */
            throw new PluginException(LinkStatus.ERROR_PLUGIN_DEFECT);
        } else {
            /* Generic errors (400/500/503/...) */
            if (link != null) {
                mhm.handleErrorGeneric(account, link, msg, 50, retryMillis);
                /* Unreachable code */
                throw new PluginException(LinkStatus.ERROR_PLUGIN_DEFECT);
            } else {
                throw new AccountUnavailableException(msg, retryMillis);
            }
        }
    }

    @Override
    public int getMaxSimultanFreeDownloadNum() {
        return 1;
    }

    @Override
    public int getMaxSimultanPremiumDownloadNum() {
        return Integer.MAX_VALUE;
    }

    @Override
    public boolean hasCaptcha(final DownloadLink link, final Account acc) {
        return false;
    }

    @Override
    protected String getAPILoginHelpURL() {
        return "https://dropx.to" + getHost();
    }

    @Override
    protected boolean looksLikeValidAPIKey(final String str) {
        // if (str == null) {
        // return false;
        // } else if (str.matches("[a-f0-9]{24}")) {
        // return true;
        // } else {
        // return false;
        // }
        return true;
    }
}
